const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());

const PORT = process.env.PORT || 3030;

const Pictures = [
  {
    id: 1,
    name: "Flamingo",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Phoenicopteriformes",
      family: "Phoenicopteridae",
      genus: "Phoenicopterus",
    },
    locations: [
      "Africa",
      "Asia",
      "Central-America",
      "Eurasia",
      "Europe",
      "North-America",
      "South-America",
    ],
    characteristics: {
      prey: "Algae, Fish, Insects",
      distinctive_feature: "Long, curved beak and sleep standing on one leg",
      wingspan: "100cm - 180cm (59in - 71in)",
      habitat: "Large lakes and plant less lagoons",
      predators: "Human, Eagles, Wild dogs",
      diet: "Omnivore",
      lifestyle: "Flock",
      favorite_food: "Algae",
      type: "Bird",
      average_clutch_size: "1",
      slogan: "Sleeps on just one leg!",
      color: "BlueWhiteOrangePink",
      skin_type: "Feathers",
      top_speed: "31 mph",
      lifespan: "15 - 30 years",
      weight: "2kg - 4kg (4.4lbs - 8.8lbs)",
      height: "100cm - 150cm (39in - 59in)",
    },
  },
  {
    id: 2,
    name: "Flamingo",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Phoenicopteriformes",
      family: "Phoenicopteridae",
      genus: "Phoenicopterus",
    },
    locations: [
      "Africa",
      "Asia",
      "Central-America",
      "Eurasia",
      "Europe",
      "North-America",
      "South-America",
    ],
    characteristics: {
      prey: "Algae, Fish, Insects",
      distinctive_feature: "Long, curved beak and sleep standing on one leg",
      wingspan: "100cm - 180cm (59in - 71in)",
      habitat: "Large lakes and plant less lagoons",
      predators: "Human, Eagles, Wild dogs",
      diet: "Omnivore",
      lifestyle: "Flock",
      favorite_food: "Algae",
      type: "Bird",
      average_clutch_size: "1",
      slogan: "Sleeps on just one leg!",
      color: "BlueWhiteOrangePink",
      skin_type: "Feathers",
      top_speed: "31 mph",
      lifespan: "15 - 30 years",
      weight: "2kg - 4kg (4.4lbs - 8.8lbs)",
      height: "100cm - 150cm (39in - 59in)",
    },
  },
  {
    id: 3,
    name: "Flamingo",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Phoenicopteriformes",
      family: "Phoenicopteridae",
      genus: "Phoenicopterus",
    },
    locations: [
      "Africa",
      "Asia",
      "Central-America",
      "Eurasia",
      "Europe",
      "North-America",
      "South-America",
    ],
    characteristics: {
      prey: "Algae, Fish, Insects",
      distinctive_feature: "Long, curved beak and sleep standing on one leg",
      wingspan: "100cm - 180cm (59in - 71in)",
      habitat: "Large lakes and plant less lagoons",
      predators: "Human, Eagles, Wild dogs",
      diet: "Omnivore",
      lifestyle: "Flock",
      favorite_food: "Algae",
      type: "Bird",
      average_clutch_size: "1",
      slogan: "Sleeps on just one leg!",
      color: "BlueWhiteOrangePink",
      skin_type: "Feathers",
      top_speed: "31 mph",
      lifespan: "15 - 30 years",
      weight: "2kg - 4kg (4.4lbs - 8.8lbs)",
      height: "100cm - 150cm (39in - 59in)",
    },
  },
  {
    id: 4,
    name: "Flamingo",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Phoenicopteriformes",
      family: "Phoenicopteridae",
      genus: "Phoenicopterus",
    },
    locations: [
      "Africa",
      "Asia",
      "Central-America",
      "Eurasia",
      "Europe",
      "North-America",
      "South-America",
    ],
    characteristics: {
      prey: "Algae, Fish, Insects",
      distinctive_feature: "Long, curved beak and sleep standing on one leg",
      wingspan: "100cm - 180cm (59in - 71in)",
      habitat: "Large lakes and plant less lagoons",
      predators: "Human, Eagles, Wild dogs",
      diet: "Omnivore",
      lifestyle: "Flock",
      favorite_food: "Algae",
      type: "Bird",
      average_clutch_size: "1",
      slogan: "Sleeps on just one leg!",
      color: "BlueWhiteOrangePink",
      skin_type: "Feathers",
      top_speed: "31 mph",
      lifespan: "15 - 30 years",
      weight: "2kg - 4kg (4.4lbs - 8.8lbs)",
      height: "100cm - 150cm (39in - 59in)",
    },
  },
  {
    id: 5,
    name: "Lemur",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Lemuridae",
      scientific_name: "Lemur Catta",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Fruit, Leaves, Insects",
      habitat: "Dry forest and tropical jungle",
      predators: "Hawk, Fossa, Wild dogs",
      diet: "Omnivore",
      average_litter_size: "3",
      lifestyle: "Group",
      favorite_food: "Fruit",
      type: "Mammal",
      slogan: "Natively found on the island of Madagascar!",
      color: "BrownGreyBlackWhite",
      skin_type: "Fur",
      top_speed: "12 mph",
      lifespan: "10-14 years",
      weight: "0.03-10kg (0.06-22lbs)",
    },
  },
  {
    id: 6,
    name: "Flamingo",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Phoenicopteriformes",
      family: "Phoenicopteridae",
      genus: "Phoenicopterus",
    },
    locations: [
      "Africa",
      "Asia",
      "Central-America",
      "Eurasia",
      "Europe",
      "North-America",
      "South-America",
    ],
    characteristics: {
      prey: "Algae, Fish, Insects",
      distinctive_feature: "Long, curved beak and sleep standing on one leg",
      wingspan: "100cm - 180cm (59in - 71in)",
      habitat: "Large lakes and plant less lagoons",
      predators: "Human, Eagles, Wild dogs",
      diet: "Omnivore",
      lifestyle: "Flock",
      favorite_food: "Algae",
      type: "Bird",
      average_clutch_size: "1",
      slogan: "Sleeps on just one leg!",
      color: "BlueWhiteOrangePink",
      skin_type: "Feathers",
      top_speed: "31 mph",
      lifespan: "15 - 30 years",
      weight: "2kg - 4kg (4.4lbs - 8.8lbs)",
      height: "100cm - 150cm (39in - 59in)",
    },
  },
  {
    id: 7,
    "name": "Spider Monkey",
    "taxonomy": {
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "class": "Mammalia",
      "order": "Primates",
      "family": "Atelidae",
      "genus": "Ateles",
      "scientific_name": "Simia Paniscus"
    },
    "locations": [
      "Central-America",
      "South-America"
    ],
    "characteristics": {
      "main_prey": "Fruit, Nuts, Leaves",
      "habitat": "Tropical jungle and rainforest",
      "predators": "Human, Eagles, Jaguar",
      "diet": "Omnivore",
      "average_litter_size": "1",
      "lifestyle": "Troop",
      "favorite_food": "Fruit",
      "type": "Mammal",
      "slogan": "Found in the tropical jungles of South America!",
      "color": "BrownGreyBlackWhite",
      "skin_type": "Hair",
      "top_speed": "35 mph",
      "lifespan": "15-27 years",
      "weight": "6.4-12kg (14-26lbs)"
    }
  },
  {
    id: 8,
    "name": "African Penguin",
    "taxonomy": {
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "class": "Aves",
      "order": "Sphenisciformes",
      "family": "Spheniscidae",
      "genus": "Spheniscus",
      "scientific_name": "Spheniscus demersus"
    },
    "locations": [
      "Africa",
      "Ocean"
    ],
    "characteristics": {
      "prey": "Fish, Squid, Crustaceans",
      "name_of_young": "Chick",
      "group_behavior": "Colony",
      "estimated_population_size": "140,000",
      "biggest_threat": "Habitat disruption",
      "most_distinctive_feature": "Pink glands above their eyes",
      "other_name(s)": "Jackass Penguin",
      "water_type": "Salt",
      "incubation_period": "40 days",
      "age_of_fledgling": "3 - 5 months",
      "habitat": "Rocky Ocean Islands",
      "predators": "Sharks, Fur Seals, Gulls",
      "diet": "Carnivore",
      "lifestyle": "Diurnal",
      "common_name": "African Penguin",
      "number_of_species": "1",
      "location": "south-west African coast",
      "average_clutch_size": "2",
      "slogan": "The only penguin species in Africa!",
      "group": "Bird",
      "color": "GreyBlackWhite",
      "skin_type": "Feathers",
      "top_speed": "12.4 mph",
      "lifespan": "10 - 15 years",
      "weight": "2kg - 5kg (4.4lbs - 11lbs)",
      "height": "60cm - 68cm (24in - 27in)",
      "age_of_sexual_maturity": "3 - 4 years"
    }
  },
  {
    id: 9,
    name: "Cheetah",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Carnivora",
      family: "Felidae",
      genus: "Acinonyx",
      scientific_name: "Acinonyx jubatus",
    },
    locations: ["Africa", "Asia", "Eurasia"],
    characteristics: {
      prey: "Gazelle, Wildebeest, Hare",
      name_of_young: "Cub",
      group_behavior: "Solitary/Pairs",
      estimated_population_size: "8,500",
      biggest_threat: "Habitat loss",
      most_distinctive_feature: "Yellowish fur covered in small black spots",
      gestation_period: "90 days",
      habitat: "Open grassland",
      diet: "Carnivore",
      average_litter_size: "3",
      lifestyle: "Diurnal",
      common_name: "Cheetah",
      number_of_species: "5",
      location: "Asia and Africa",
      slogan: "The fastest land mammal in the world!",
      group: "Mammal",
      color: "BrownYellowBlackTan",
      skin_type: "Fur",
      top_speed: "70 mph",
      lifespan: "10 - 12 years",
      weight: "40kg - 65kg (88lbs - 140lbs)",
      height: "115cm - 136cm (45in - 53in)",
      age_of_sexual_maturity: "20 - 24 months",
      age_of_weaning: "3 months",
    },
  },
  {
    id: 10,
    name: "Kestrel",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Aves",
      order: "Falconiformes",
      family: "Falconidae",
      genus: "Falco",
      scientific_name: "Falco sparverius",
    },
    locations: ["Africa", "Asia", "Europe", "North-America", "South-America"],
    characteristics: {
      prey: "Small rodents, lizards, insects, birds, and eggs",
      estimated_population_size: "9.2 million",
      biggest_threat: "Starvation",
      most_distinctive_feature: "Hunting behavior of hovering and diving",
      "other_name(s)":
        "Grasshopper hawk, killy hawk, short-winged hawk, windhover, house hawk, and rusty-crowned falcon",
      wingspan: "20-31in",
      incubation_period: "30 days",
      habitat: "Open countryside",
      predators: "Larger birds of prey, snakes, fire ants, and cats",
      diet: "Carnivore",
      average_litter_size: "3-7",
      type: "Bird",
      common_name: "Sparrowhawk",
      number_of_species: "15",
      location: "North America, most of South America, Europe, Asia, Africa",
      nesting_location: "Natural cavities, other birds' nests, nesting boxes",
      age_of_molting: "The next spring (adults molt in the fall)",
      migratory: "1",
      color: "BrownBlack",
      top_speed: "39 mph",
      lifespan: "5 years in the wild, 17 years in captivity",
      weight: "2.8-6.5oz",
      height: "Unknown",
      length: "8.7-15in",
    },
  },
];

app.get("/api", (req, res) => {
  res.json(Pictures);
});

app.get("/api/:id", (req, res) => {
  const id = parseInt(req.params.id);
  const picture = Pictures.find((picture) => picture.id === id);

  if (picture) {
    res.json(picture);
  } else {
    res.status(404).json({ message: "Image not found" });
  }
});

app.listen(PORT, () => {
  console.log(`server started on port ${PORT}`);
});
